version: '3.9'

services:
  app:
    build: .
    container_name: crawler-app
    ports:
      - "9999:9999"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      PORT: 9999
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npx ts-node index.ts -y"
    cap_add:
      - SYS_ADMIN 
    shm_size: 1gb

  db:
    image: postgres:15
    container_name: crawler-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
